[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sat = "GoyGGBpwUQYxoicpFRiNQ8k8qKk1myVRDkiiLvXaT1jg"

[programs.devnet]
sat = "GoyGGBpwUQYxoicpFRiNQ8k8qKk1myVRDkiiLvXaT1jg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
